import type { MetadataRoute } from "next";

/**
 * PWA manifest, generated by Next so it stays in sync with app metadata.
 *
 * `display: standalone` matters at the counter: the app opens without browser
 * chrome, so a cashier cannot accidentally navigate away mid-sale.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "PharmaDaily — Pharmacy Management",
    short_name: "PharmaDaily",
    description:
      "Multi-branch pharmacy management: inventory, billing, purchases and reporting. Keeps billing running offline.",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: "#ffffff",
    theme_color: "#0a0a0a",
    categories: ["business", "medical", "productivity"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
