-- ---------------------------------------------------------------------------
-- Phase 2 / 4 — purchases and purchase_items
--
-- A purchase is the paperwork for a consignment arriving at one branch.
-- Receiving it is what creates or tops up branch_stocks rows; see the
-- create_purchase() function for the transaction that keeps the two in step.
-- ---------------------------------------------------------------------------

create table public.purchases (
  id uuid primary key default gen_random_uuid(),

  supplier_id uuid not null references public.suppliers (id) on delete restrict,
  branch_id uuid not null references public.branches (id) on delete restrict,

  purchase_date date not null default current_date,

  -- The SUPPLIER's invoice number, typed in from their paperwork — not
  -- generated by us. (Phase 3's sales invoice numbers are ours, and are
  -- generated.) Unique per supplier so the same consignment cannot be
  -- received twice by mistake, which would double the stock.
  invoice_no text not null,

  total_amount numeric(14, 2) not null default 0,
  paid_amount numeric(14, 2) not null default 0,
  due_amount numeric(14, 2) not null default 0,

  notes text,

  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  constraint purchases_invoice_no_not_blank check (length(btrim(invoice_no)) > 0),
  constraint purchases_amounts_non_negative
    check (total_amount >= 0 and paid_amount >= 0 and due_amount >= 0),
  constraint purchases_paid_within_total check (paid_amount <= total_amount),
  -- The ledger must balance on every row, so a partial write can never leave
  -- a purchase whose due does not reconcile with what was paid.
  constraint purchases_due_balances check (due_amount = total_amount - paid_amount)
);

create unique index purchases_supplier_invoice_unique
  on public.purchases (supplier_id, lower(btrim(invoice_no)))
  where deleted_at is null;

create index purchases_branch_date_idx
  on public.purchases (branch_id, purchase_date desc)
  where deleted_at is null;

create index purchases_supplier_idx on public.purchases (supplier_id) where deleted_at is null;

create trigger set_purchases_updated_at
  before update on public.purchases
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------

create table public.purchase_items (
  id uuid primary key default gen_random_uuid(),

  purchase_id uuid not null references public.purchases (id) on delete cascade,
  medicine_id uuid not null references public.medicines (id) on delete restrict,

  batch_no text not null,
  expiry_date date not null,
  quantity integer not null,
  cost_price numeric(12, 2) not null,

  -- Captured at receipt so the batch's retail pricing is part of the
  -- paperwork, not something re-entered later.
  selling_price numeric(12, 2) not null,
  mrp numeric(12, 2) not null,

  created_at timestamptz not null default now(),

  constraint purchase_items_batch_no_not_blank check (length(btrim(batch_no)) > 0),
  constraint purchase_items_quantity_positive check (quantity > 0),
  constraint purchase_items_prices_non_negative
    check (cost_price >= 0 and selling_price >= 0 and mrp >= 0)
);

-- ON DELETE CASCADE above is safe precisely because purchases are soft-deleted
-- and never hard-deleted by the application; it exists only so that a genuine
-- administrative hard delete cannot strand orphan line items.

create index purchase_items_purchase_idx on public.purchase_items (purchase_id);
create index purchase_items_medicine_idx on public.purchase_items (medicine_id);

comment on column public.purchases.invoice_no is
  'The supplier''s own invoice number, entered by staff. Unique per supplier to prevent receiving the same consignment twice.';
