-- ---------------------------------------------------------------------------
-- Phase 3 / 2 — sales, sale_items, payments
-- ---------------------------------------------------------------------------

create type public.payment_method as enum ('cash', 'bkash', 'nagad', 'card', 'due');

-- ---------------------------------------------------------------------------

create table public.sales (
  id uuid primary key default gen_random_uuid(),

  branch_id uuid not null references public.branches (id) on delete restrict,
  customer_id uuid references public.customers (id) on delete restrict,
  cashier_id uuid references public.profiles (id) on delete set null,

  -- BRANCHCODE-YYYY-XXXX, generated by next_invoice_no(). Human-readable,
  -- branch-unique and sequential per year, so a missing number in a sequence
  -- is visible during an audit.
  invoice_no text not null,

  subtotal numeric(14, 2) not null default 0,
  discount numeric(14, 2) not null default 0,
  total_amount numeric(14, 2) not null default 0,
  paid_amount numeric(14, 2) not null default 0,
  due_amount numeric(14, 2) not null default 0,

  sale_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  constraint sales_invoice_no_not_blank check (length(btrim(invoice_no)) > 0),
  constraint sales_amounts_non_negative check (
    subtotal >= 0 and discount >= 0 and total_amount >= 0
    and paid_amount >= 0 and due_amount >= 0
  ),
  constraint sales_discount_within_subtotal check (discount <= subtotal),

  -- The two arithmetic identities every sale must satisfy. Enforced here so a
  -- partial write or a future code path cannot produce a row whose numbers do
  -- not add up — these figures feed every financial report.
  constraint sales_total_balances check (total_amount = subtotal - discount),
  constraint sales_due_balances check (due_amount = total_amount - paid_amount)
);

-- Invoice numbers must be unique per branch. Not globally unique: two branches
-- legitimately have DHK-2026-0001 and CTG-2026-0001.
create unique index sales_branch_invoice_unique
  on public.sales (branch_id, invoice_no)
  where deleted_at is null;

create index sales_branch_date_idx
  on public.sales (branch_id, sale_date desc, created_at desc)
  where deleted_at is null;

create index sales_customer_idx on public.sales (customer_id) where deleted_at is null;
create index sales_cashier_idx on public.sales (cashier_id) where deleted_at is null;

-- The POS looks a sale up by invoice number when processing a return, and
-- staff type it without worrying about case.
create index sales_invoice_lookup_idx on public.sales (upper(invoice_no));

create trigger set_sales_updated_at
  before update on public.sales
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------

create table public.sale_items (
  id uuid primary key default gen_random_uuid(),

  sale_id uuid not null references public.sales (id) on delete cascade,
  medicine_id uuid not null references public.medicines (id) on delete restrict,

  -- Points at the exact batch row, not just medicine + batch_no. A return has
  -- to restock the same physical batch it came from, and resolving that by
  -- matching two columns would be ambiguous the moment a batch number repeats
  -- across suppliers.
  branch_stock_id uuid not null references public.branch_stocks (id) on delete restrict,
  batch_no text not null,

  quantity integer not null,
  unit_price numeric(12, 2) not null,
  total_price numeric(14, 2) not null,

  created_at timestamptz not null default now(),

  constraint sale_items_quantity_positive check (quantity > 0),
  constraint sale_items_prices_non_negative check (unit_price >= 0 and total_price >= 0),
  constraint sale_items_total_balances check (total_price = unit_price * quantity)
);

create index sale_items_sale_idx on public.sale_items (sale_id);
create index sale_items_medicine_idx on public.sale_items (medicine_id);
create index sale_items_stock_idx on public.sale_items (branch_stock_id);

-- ---------------------------------------------------------------------------

create table public.payments (
  id uuid primary key default gen_random_uuid(),

  sale_id uuid not null references public.sales (id) on delete cascade,
  branch_id uuid not null references public.branches (id) on delete restrict,

  method public.payment_method not null,
  amount numeric(14, 2) not null,

  -- bKash/Nagad transaction id, card authorisation code. Filled in properly by
  -- the Phase 6 gateway integration; typed in by hand until then.
  reference text,

  created_at timestamptz not null default now(),

  constraint payments_amount_positive check (amount > 0)
);

-- A sale can have several rows here: half cash, half bKash. That is what makes
-- mixed payment possible without a special case in the schema.
create index payments_sale_idx on public.payments (sale_id);
create index payments_branch_created_idx on public.payments (branch_id, created_at desc);

comment on table public.payments is
  'One row per tender. Multiple rows per sale is how mixed payment works.';
comment on column public.sale_items.branch_stock_id is
  'The exact batch row sold, so a return restocks precisely what left the shelf.';
